### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Blackbird88** [Phrohdoh/oramod-ra2#96] opened 2015-07-11 09:17 UTC
I have language.mix, ra2.mix and theme.mix in c:\Users\name\Documents\OpenRA\Content\ra2\
They're from C&C Complete collection from Origin which should be same as First Decade.
Compiled latest OpenRA myself.

```
Red Alert 2 Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.0
Exception of type `System.InvalidOperationException`: Cannot locate type: RenderUnitInfo
   v OpenRA.ObjectCreator.<.cctor>b__13(String s) v d:\OpenRA\OpenRA.Game\ObjectCreator.cs:řádek 46
   v OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args) v d:\OpenRA\OpenRA.Game\ObjectCreator.cs:řádek 58
   v OpenRA.ActorInfo.LoadTraitInfo(String traitName, MiniYaml my) v d:\OpenRA\OpenRA.Game\GameRules\ActorInfo.cs:řádek 96
   v OpenRA.ActorInfo..ctor(String name, MiniYaml node, Dictionary`2 allUnits) v d:\OpenRA\OpenRA.Game\GameRules\ActorInfo.cs:řádek 52
   v OpenRA.RulesetCache.<Load>b__0(MiniYamlNode k, Dictionary`2 y) v d:\OpenRA\OpenRA.Game\GameRules\RulesetCache.cs:řádek 64
   v OpenRA.RulesetCache.<>c__DisplayClass15`1.<LoadYamlRules>b__10(MiniYamlNode wkv, Dictionary`2 wyy) v d:\OpenRA\OpenRA.Game\GameRules\RulesetCache.cs:řádek 113
   v OpenRA.RulesetCache.<>c__DisplayClass15`1.<LoadYamlRules>b__14(MiniYamlNode kv) v d:\OpenRA\OpenRA.Game\GameRules\RulesetCache.cs:řádek 121
   v OpenRA.Exts.ToDictionaryWithConflictLog[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, String debugName, Func`2 logKey, Func`2 logValue) v d:\OpenRA\OpenRA.Game\Exts.cs:řádek 365
   v OpenRA.RulesetCache.LoadYamlRules[T](Dictionary`2 itemCache, String[] files, List`1 nodes, Func`3 f) v d:\OpenRA\OpenRA.Game\GameRules\RulesetCache.cs:řádek 121
   v OpenRA.RulesetCache.Load(Map map) v d:\OpenRA\OpenRA.Game\GameRules\RulesetCache.cs:řádek 62
   v OpenRA.ModData.<.ctor>b__2() v d:\OpenRA\OpenRA.Game\ModData.cs:řádek 82
   v System.Lazy`1.CreateValue()
   v System.Lazy`1.LazyInitValue()
   v System.Lazy`1.get_Value()
   v OpenRA.Map.<PostInit>b__b() v d:\OpenRA\OpenRA.Game\Map\Map.cs:řádek 403
   v System.Lazy`1.CreateValue()
   v System.Lazy`1.LazyInitValue()
   v System.Lazy`1.get_Value()
   v OpenRA.ModData.PrepareMap(String uid) v d:\OpenRA\OpenRA.Game\ModData.cs:řádek 169
   v OpenRA.Game.StartGame(String mapUID, WorldType type) v d:\OpenRA\OpenRA.Game\Game.cs:řádek 148
   v OpenRA.Game.LoadShellMap() v d:\OpenRA\OpenRA.Game\Game.cs:řádek 377
   v OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   v OpenRA.Game.InitializeMod(String mod, Arguments args) v d:\OpenRA\OpenRA.Game\Game.cs:řádek 364
   v OpenRA.Game.Initialize(Arguments args) v d:\OpenRA\OpenRA.Game\Game.cs:řádek 253
   v OpenRA.Program.Run(String[] args) v d:\OpenRA\OpenRA.Game\Support\Program.cs:řádek 109
   v OpenRA.Program.Main(String[] args) v d:\OpenRA\OpenRA.Game\Support\Program.cs:řádek 39
```

**Comment by abcdefg30** [comment] 2015-07-11 11:14
Thanks for the report!
The issue should be fixed now: https://github.com/Phrohdoh/oramod-ra2/commit/c87d8ff6060b6d73cb709638b41f19b08d6c498c

**Closed by abcdefg30** 2015-07-11 11:14 UTC

**Comment by Blackbird88** [comment] 2015-07-11 12:39
Fixed indeed, but now I get crash when right-clicking on MCV unless that isn't implemented yet?
```
Red Alert 2 Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.0
Exception of type `System.InvalidOperationException`: Can't find Action in voice pool.
   v OpenRA.Sound.PlayPredefined(Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume) v d:\OpenRA\OpenRA.Game\Sound\Sound.cs:řádek 333
   v OpenRA.Mods.Common.Traits.Voiced.PlayVoice(Actor self, String phrase, String variant)
   v OpenRA.VoiceExts.PlayVoiceForOrders(World w, Order[] orders) v d:\OpenRA\OpenRA.Game\VoiceExts.cs:řádek 68
   v OpenRA.Widgets.WorldInteractionControllerWidget.ApplyOrders(World world, MouseInput mi) v d:\OpenRA\OpenRA.Game\Widgets\WorldInteractionControllerWidget.cs:řádek 176
   v OpenRA.Widgets.WorldInteractionControllerWidget.HandleMouseInput(MouseInput mi) v d:\OpenRA\OpenRA.Game\Widgets\WorldInteractionControllerWidget.cs:řádek 143
   v OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) v d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:řádek 354
   v OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) v d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:řádek 345
   v OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) v d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:řádek 345
   v OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) v d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:řádek 345
   v OpenRA.Widgets.Ui.HandleInput(MouseInput mi) v d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:řádek 90
   v OpenRA.DefaultInputHandler.<>c__DisplayClass7.<OnMouseInput>b__6() v d:\OpenRA\OpenRA.Game\Input\InputHandler.cs:řádek 49
   v OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) v d:\OpenRA\OpenRA.Game\Sync.cs:řádek 185
   v OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) v d:\OpenRA\OpenRA.Game\Input\InputHandler.cs:řádek 49
   v OpenRA.Renderer.Sdl2.Sdl2Input.PumpInput(IInputHandler inputHandler) v d:\OpenRA\OpenRA.Renderer.Sdl2\Sdl2Input.cs:řádek 86
   v OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler) v d:\OpenRA\OpenRA.Renderer.Sdl2\Sdl2GraphicsDevice.cs:řádek 359
   v OpenRA.Graphics.Renderer.EndFrame(IInputHandler inputHandler) v d:\OpenRA\OpenRA.Game\Graphics\Renderer.cs:řádek 152
   v OpenRA.Game.RenderTick() v d:\OpenRA\OpenRA.Game\Game.cs:řádek 547
   v OpenRA.Game.Loop() v d:\OpenRA\OpenRA.Game\Game.cs:řádek 654
   v OpenRA.Game.Run() v d:\OpenRA\OpenRA.Game\Game.cs:řádek 672
   v OpenRA.Program.Run(String[] args) v d:\OpenRA\OpenRA.Game\Support\Program.cs:řádek 111
   v OpenRA.Program.Main(String[] args) v d:\OpenRA\OpenRA.Game\Support\Program.cs:řádek 39
```

**Comment by Phrohdoh** [comment] 2015-07-11 13:08
Another user had this error in TS but I'm not sure how he resolved it.
I'll try to get in contact with him.

**Comment by Blackbird88** [comment] 2015-07-11 13:20
TS works fine here so you sure it's the same issue?

**Comment by Phrohdoh** [comment] 2015-07-11 13:36
Yes it is the same stacktrace. RA2 is always a little behind upstream, as this user was, meaning his fix ought to fix this issue as well.

**Comment by Phrohdoh** [comment] 2015-07-11 14:13
This is the cause: https://github.com/OpenRA/OpenRA/commit/50e5e9df248966d564c4938613b40a6ca71ea677#diff-e0fb96913b232d6667aea6c6b570e15cR29

**Comment by Blackbird88** [comment] 2015-07-12 11:34
Oh yeah it's something to do with Units sounds alright
http://i.imgur.com/oDYjoBC.jpg?1

**Comment by abcdefg30** [comment] 2015-07-12 12:10
Which version of OpenRA are you using? This repo should be set up for the last release.

**Comment by Blackbird88** [comment] 2015-07-12 12:12
Latest git repo as it's advised in README.MD

**Comment by abcdefg30** [comment] 2015-07-12 12:15
> Latest git repo as it's advised in README.MD

Do you mean the submodule?

**Comment by Blackbird88** [comment] 2015-07-12 12:19
No OpenRA itself. Is the submodule referencing specific repo or something?

**Comment by abcdefg30** [comment] 2015-07-12 12:22
The submodule is referencing a specific version of the OpenRA repo.

**Comment by Blackbird88** [comment] 2015-07-12 12:23
Well that would explain some stuff. Guess I'll get to this later. I don't see 2 OpenRAs that much.

**Comment by Phrohdoh** [comment] 2015-07-12 13:35
If you guys give me a bit of time I'll have all of this fixed. phrohdoh/OpenRA/ra2-master doesn't have these errors.

**Comment by Blackbird88** [comment] 2015-07-12 13:40
Great to hear :)
Good lucking fixing those pesky errors!

**Comment by Phrohdoh** [comment] 2015-07-12 13:44
@Blackbird88 you're also free to join the RA2 team on IRC at `#orcaware` on freenode.
Discussing fixes/features is much easier there. :)

**Comment by Blackbird88** [comment] 2015-07-12 13:51
I'd like to, but I'm not a programmer really :D
Just a guy that has OCD about things.

**Comment by GraionDilach** [comment] 2015-07-12 14:15
Building beeping sound?

**Comment by Blackbird88** [comment] 2015-07-12 14:22
Ticking sound? Dunno how it's called really. When building is in progress.

**Comment by Phrohdoh** [comment] 2015-07-12 14:33
Use a new ticket or IRC please.

**Comment by Blackbird88** [comment] 2015-07-12 14:34
Sure no problem. Was just clarifying.

**Comment by GraionDilach** [comment] 2015-07-12 14:59
That's the money-being-spent beep and yes, RA2 has it. The difference between the two games here is that RA2 always interrupted -and-restarted that one sound while OpenRA plays multiple instances side-by-side which leads to the different sounding.

**Comment by Blackbird88** [comment] 2015-07-12 15:02
Odd. I just launched real RA2 to check and there is no sound at all.

**Comment by GraionDilach** [comment] 2015-07-12 15:06
See https://github.com/Phrohdoh/oramod-ra2/blob/master/extra-files/rules.ini#L565 and https://github.com/Phrohdoh/oramod-ra2/blob/master/extra-files/sound.ini#L3147.

Your RA2 must be modded/tampered with.

**Comment by Blackbird88** [comment] 2015-07-12 15:07
It's default install from Origin.

**Comment by GraionDilach** [comment] 2015-07-12 15:12
Well, then maybe it's caused by the volume difference - default volume is 85 in RA2 compared to that 20/30 they're set.

The sound definitely existed. I guess it's related when people complain about the ore drilling sound getting "enabled" in mods - that wasn't enough loud in default game for people to notice it exists neither.

**Comment by Blackbird88** [comment] 2015-07-12 15:13
That is possible indeed, but default sliders don't do anything.

**Comment by GraionDilach** [comment] 2015-07-12 15:41
Turn off Settings-Audio-Cash Ticks then.

**Comment by Blackbird88** [comment] 2015-07-12 15:42
But isn't that Global for all games in OpenRA?

**Comment by GraionDilach** [comment] 2015-07-12 15:44
It is, but that controls the particular sounds, so that's your only control for it for now.

**Comment by Blackbird88** [comment] 2015-07-12 15:45
Oh well guess that'll do for now :)
